version: '3.4'

services:
  spotifydownload:
    image: spotifydownload
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 mbot/__init__.py "]
    ports:
      - 5678:5678
